server:
  address: 0.0.0.0
  port: 8084
logging:
  level:
    root: info
spring:
  application:
    name: taxi-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taxi_db
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      # 服务发现
      discovery:
        server-addr: 127.0.0.1:8848
      # 注册中心
      config:
        server-addr: 127.0.0.1:8848
seata:
  tx-service-group: app-taxi
  service:
    vgroup-mapping:
      app-taxi: default
    grouplist:
      default: localhost:8091