server:
  address: 0.0.0.0
  port: 8082
logging:
  level:
    root: info
    com:
      example:
        taxiorder: debug
spring:
  application:
    name: taxi-driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taxi_db
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      # 服务发现
      discovery:
        server-addr: 127.0.0.1:8848
      # 注册中心
      config:
        server-addr: 127.0.0.1:8848
feign:
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/html,json/application,xml/application
    response:
      enabled: true