server:
  address: 0.0.0.0
  port: 8083
logging:
  level:
    root: info
    com:
      example:
        taxiorder: debug
spring:
  application:
    name: taxi-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taxi_db
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      # 服务发现
      discovery:
        server-addr: 127.0.0.1:8848
      # 注册中心
      config:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # 通过浏览器进行http访问的地址
        dashboard: localhost:8791
        # 配置的sentinel server api port，默认8719
        port: 8719
# 只有feign的客户端需要配置这个
feign:
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/html,json/application,xml/application
    response:
      enabled: true
  # 浏览器中dashboard的地址
  sentinel:
    enabled: true
seata:
  tx-service-group: app-taxi
  service:
    vgroup-mapping:
      app-taxi: default
    grouplist:
      default: localhost:8091